export const projects = [
  {
    title: 'DALClub',
    description: 'Full Stack Web Application for a club.',
    image: '/images/dalclub.png',
    tags: [
      'HTML',
      'CSS',
      'Javascript',
      'React.js',
      'Node.js',
      'Material UI',
      'Styled Components',
      'Express',
      'Sequelize',
      'MySQL',
      'Stripe',
      'GitLab',
      'JIRA',
      'Heroku',
    ],
    source: 'https://github.com/RahulKherajani/dalclub',
    visit: 'https://web-dalclub.herokuapp.com/',
    id: 0,
  },
  {
    title: 'fleaMART',
    description: 'Full Stack Web Application for a Online Marketplace',
    image: '/images/fleamart.png',
    tags: [
      'HTML',
      'CSS',
      'Javascript',
      'React.js',
      'Material UI',
      'Styled Components',
      'Spring Boot',
      'AWS Elastic Beanstalk',
      'AWS Lambda',
      'Amazon S3',
      'Amazon DynamoDB',
      'Amazon API Gateway',
      'Amazon Cognito',
      'Amazon SNS',
      'AWS Amplify',
      'Gitlab',
      'JIRA',
    ],
    source: 'https://github.com/RahulKherajani/fleamart',
    visit: 'https://main.d29fadnnqs0sgt.amplifyapp.com/',
    id: 1,
  },
  {
    title: 'HEALTH-e-ME',
    description: 'Full Stack Web Application for Health & Wellness App',
    image: '/images/healtheme.png',
    tags: [
      'HTML',
      'CSS',
      'Javascript',
      'Java',
      'Spring Boot',
      'Thymeleaf',
      'MySQL',
      'Gradle',
      'Gitlab',
      'JIRA',
      'Heroku',
      'Test Driven Development',
      'SOLID Principles',
      'Design Patterns',
    ],
    source: 'https://github.com/RahulKherajani/health-e-me',
    visit: 'https://healtheme-prod.herokuapp.com/',
    id: 2,
  },
  {
    title: 'CentDB',
    description:
      'centralized DBMS that supports SQL queries and CRUD operations on data',
    image: '/images/centdb.png',
    tags: [
      'Java',
      'Java Collections',
      'Maven',
      'Gitlab',
      'JIRA',
      'Data Structures',
    ],
    source: 'https://github.com/RahulKherajani/centdb',
    visit: '',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Started my journey' },
  { year: 2018, text: 'Worked as a freelance developer' },
  { year: 2019, text: 'Founded JavaScript Mastery' },
  { year: 2020, text: 'Shared my projects with the world' },
  { year: 2021, text: 'Started my own platform' },
];
